### ISSUE TITLE
npm start fails if mongodb not installed

### ISSUE THREAD

**Issue by heyitsjames** [antonshevchenko/pager#1]
Here is the error that occured:

```
> pager@0.0.1 start /Users/<user_folder>/projects/misc/pager
> mkdir -p ./data/db | mongod --dbpath ./data/db | nodemon server

sh: mongod: command not found
3 May 22:06:09 - [nodemon] v1.3.7
3 May 22:06:09 - [nodemon] to restart at any time, enter `rs`
3 May 22:06:09 - [nodemon] watching: *.*
3 May 22:06:09 - [nodemon] starting `node server server.js`
Listening on port: 3000

/Users/<user_folder>/projects/misc/pager/node_modules/mongoose/node_modules/mongodb/lib/server.js:228
        process.nextTick(function() { throw err; })
                                            ^
Error
    at Error.MongoError (/Users/<user_folder>/projects/misc/pager/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/error.js:13:17)
    at Server.destroy (/Users/<user_folder>/projects/misc/pager/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:629:47)
    at Server.close (/Users/<user_folder>/projects/misc/pager/node_modules/mongoose/node_modules/mongodb/lib/server.js:344:17)
    at Db.close (/Users/<user_folder>/projects/misc/pager/node_modules/mongoose/node_modules/mongodb/lib/db.js:267:19)
    at /Users/<user_folder>/projects/misc/pager/node_modules/mongoose/node_modules/mongodb/lib/db.js:196:12
    at null.<anonymous> (/Users/<user_folder>/projects/misc/pager/node_modules/mongoose/node_modules/mongodb/lib/server.js:226:9)
    at g (events.js:180:16)
    at emit (events.js:98:17)
    at null.<anonymous> (/Users/<user_folder>/projects/misc/pager/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:238:68)
    at g (events.js:180:16)
3 May 22:06:10 - [nodemon] app crashed - waiting for file changes before starting...
```

doing a `brew install mongodb` fixed the problem. Consider adding that as a dependency in `package.json` or elsewhere

**Comment by dominickolbe** [comment]
Thanks!

**Comment by antonshevchenko** [comment]
@heyitsjames I'm not sure that mongodb can be installed using NPM. If so, let me know what dependency it is and we will surely add it to the `package.json`!

**Comment by antonshevchenko** [comment]
Closing for now...
